[package]
name = "Snake-With-Q-Learning"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = "0.13"
winit = "0.28"
winit_input_helper = "0.14"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ahash = { version = "0.8", features = ["serde"] }

