# cargo-deny configuration
# Docs: https://embarkstudios.github.io/cargo-deny/

[graph]
# Skip dev-dependencies for license/advisory checks in release builds
# (CI job can choose to include them if desired)
all-features = false
no-default-features = false
features = []

[advisories]
# Audit RustSec advisories
# In recent cargo-deny versions vulnerability/notice are implicit errors; configure remaining knobs
unmaintained = "workspace" # one of: "all", "workspace", "transitive", "none"
yanked = "warn"
# You can curate an ignore list per-advisory ID here, with notes and expiry
# ignore = [
#   { id = "RUSTSEC-2020-0071", reason = "transitive via X, not used at runtime", until = "2026-01-01" }
# ]

[licenses]
# Allowlist common permissive and weak-copyleft licenses
allow = [
  "MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause",
  "ISC", "Zlib", "Unicode-DFS-2016", "CC0-1.0",
  # Needed by gfx/wgpu stack (e.g., naga)
  "MPL-2.0",
  # Some crates use this variant
  "Apache-2.0 WITH LLVM-exception",
]

# You can add crate-specific exceptions with the array field below if needed
# exceptions = [
#   { crate = "some-crate", allow = ["BSD-2-Clause"] },
# ]

[licenses.private]
# If you have private crates in a workspace, configure as needed
ignore = false



[bans]
# Detect multiple versions of the same crate
multiple-versions = "warn"
# Deny wildcard dependencies like foo = "*"
wildcards = "deny"
# Explicit allows if needed:
# allow = [
#   { name = "time", version = "0.3" },
# ]

[sources]
# Forbid git dependencies by default in releases (prefer crates.io)
unknown-registry = "deny"
unknown-git = "deny"
# Allow crates.io
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# Allow specific git sources if needed
# allow-git = ["https://github.com/your-org/your-repo.git"]


